kubernetes-csi/csi-test

utils/grpcutil.go

More reliable connections

---

hack/e2e.sh
pkg/sanity/controller.go
pkg/sanity/identity.go
pkg/sanity/sanity.go

This change has seems to have found an error in the mock driver,
so until we find out the issue, the tests will be skipped in
`hack/e2e.sh` with `--ginkgo.skip=MOCKERRORS`.
Also introduced more reliable connection to the CSI driver
by only creating a single connection once during the test.

sanity: CreateVolume

---

pkg/sanity/controller.go
pkg/sanity/node.go

sanity: Add cleanup code

---

hack/e2e.sh

CSI spec 0.2.0 changes made it to master branch of GoCSI, and support/csi-0.2.0 branch was removed.

Switching to master branch got GoCSI

---

mock/service/controller.go
mock/service/node.go
mock/service/service.go
pkg/sanity/controller.go
pkg/sanity/node.go

Refactor mock driver to be in sync with the CSI spec

Mock refactor

---

mock/service/controller.go
pkg/sanity/controller.go

Starting to cleanup and adjust e2e tests according to proposed e2e test list. (Controller related tests)

Controller: cleaning up e2e tests

---

mock/service/controller.go
pkg/sanity/controller.go

Continuing mock driver return codes cleanup.

Controller Publish/Unpublish cleanup

---

cmd/csi-sanity/sanity_test.go
pkg/sanity/controller.go
pkg/sanity/node.go
pkg/sanity/sanity.go

Existing tests do not support drivers with STAGE_UNSTAGE_VOLUME capability.
Additionally there was a duplicate test in `NodeUnpublishVolume` with one in `NodePublishVolume`.  I deleted the duplicate version. More details for long-term fix in #52 
/assign @lpabon @sbezverk

Fixes for drivers with STAGE_UNSTAGE_VOLUME capability

---

cmd/csi-sanity/sanity_test.go
pkg/sanity/controller.go
pkg/sanity/node.go
pkg/sanity/sanity.go

Change arguments to Test to a struct

---

pkg/sanity/sanity.go

Mkdir will fail when required parent path does not exist. MkdirAll creates the full directory structure required by Target and Staging path.

Changed Mkdir to create full directory. Also creates Staging Path

---

pkg/sanity/controller.go

The Spec on required bytes:
// Volume must be at least this big. This field is OPTIONAL.
// A value of 0 is equal to an unspecified field value.
// The value of this field MUST NOT be negative. 
int64 required_bytes = 1;
Therefore tests should accept any CreateVolume return size greater than or equal to the required bytes size.

Testing with 'RequiredBytes' should use it as a minimum value according to spec

---

pkg/sanity/controller.go

Added test volume size constant, fixed 'should fail when requesting to create a volume with already exisiting name and different capacity.' to have stricter size requests. 
Previously because only request was defined, first call could have resulted in a larger provisioned disk which would have potentially still satisfied the second request.
Ex.
Request: 5 gig
Disk Provisioned: 10gig
[Supposed to fail disk of same name] Request: 7gig
This was completely following the spec but would have failed the test.

Made a CreateVolume test stricter so that some CSI compliant drivers wont fail

---

mock/service/node.go
pkg/sanity/node.go

sanity: Add tests for NodeStageVolume/NodeUnstageVolume

---

Gopkg.lock
Gopkg.toml
cmd/csi-sanity/README.md
cmd/csi-sanity/sanity_test.go
driver/driver.go
hack/e2e.sh
mock/main.go
mock/mocksecret.yaml
pkg/sanity/controller.go
pkg/sanity/node.go
pkg/sanity/sanity.go

Adds auth interceptor in mock driver to check the passed credentials.
Adds secrets support in csi-sanity via yaml file with secret config.
Inserts secrets in all the test request when secrets are defined.
Runs the whole e2e test suite second time with credentials set.
Fixes #47

Add CSI crentials tests

---

cmd/csi-sanity/sanity_test.go
pkg/sanity/controller.go
pkg/sanity/sanity.go

Not all CSI drivers necessarily support 10GB volumes. Some simplistic,
memory-backed test drivers for example might only work with some
smaller size.

sanity: configurable volume size

---

mock/service/controller.go
pkg/sanity/controller.go

Adds tests for:
* should fail when the volume does not exist
* should fail when the node does not exist
* should fail when the volume is already published but is incompatible
Also, modifies mock driver to contain readonly volume information.

sanity: Add more ControllerPublishVolume tests

---

mock/service/identity.go
pkg/sanity/identity.go

CSI 0.3.0 introduced probe ready status. This change adds the Ready
value in ProbeResponse.

Mock driver: Return probe ready status

---

pkg/sanity/controller.go

Adds ValidateVolumeCapabilities controller test to ensure that the
validation fails when a non-existent volume ID is requested for volume
capability validation.

sanity: ValidateVolumeCapabilities test for no volume

---

pkg/sanity/identity.go
pkg/sanity/node.go

* Adds test for NodeGetInfo()
* Adds ACCESSIBILITY_CONSTRAINT plugin capability in the known plugin
capability list.
* Adds isPluginCapabilitySupported() to check if the
ACCESSIBILITY_CONSTRAINT plugin capability is supported.

sanity: test NodeGetInfo() & accessibility capability

---

test/co_test.go

I'm opening this PR to demonstrate an error I am seeing with `csi-test` master. When updating the CSI external attacher/detacher, I always get a test failure for ControllerPublishVolume. In fact it hangs - took a while to track it down to this.
The `reflect.DeepEqual` that `gomock` performs to check for object equivalence is failing for the `ControllerPublishVolume` input. Oddly, it is *only* that call that fails - all the other tests pass. For simplicity, I added a test here in `csi-test` that demonstrates it.
When the test fails, you will see the following:
```
Unexpected call to *driver.MockControllerServer.ControllerPublishVolume([context.Background.WithCancel.WithCancel.WithValue(peer.peerKey{}, &peer.Peer{Addr:(*net.TCPAddr)(0xc4201b0c60), …
```

Add test for ControllerPublishVolume

---

pkg/sanity/node.go

Pass volume attributes to ControllerPublish, NodeStage, NodePublish

---

pkg/sanity/README.md
pkg/sanity/controller.go
pkg/sanity/identity.go
pkg/sanity/node.go
pkg/sanity/sanity.go
pkg/sanity/tests.go

This was not possible before:
- Ginkgo only supports one set of Before/AfterSuite calls,
which might be in use already in the existing suite (for
example, the Kubernetes e2e framework).
- When nesting the sanity test inside a Ginkgo spec there
is no testing.T pointer that could be passed to
the Test method.
Now all global variables are replaced with a test context that gets
passed into the specs explicitly. For this to work, specs must be set
up with SanityDescribe instead of the previous Describe call.
The Test and Config API are unchanged, but there is one slight change
of behavior: previously it was possible to define two tests with
different configs in the same test binary and then running each test
would execute the sanity tests for that config. That no longer works
because running …

pkg/sanity: support sanity testing in another Ginkgo suite

---

driver/driver.go
mock/cache/SnapshotCache.go
mock/mocksecret.yaml
mock/service/controller.go
mock/service/service.go
pkg/sanity/controller.go
pkg/sanity/sanity.go

add test for volume snapshot

---

.travis.yml
Makefile
driver/driver.go
hack/e2e.sh
pkg/sanity/cleanup.go
pkg/sanity/controller.go
pkg/sanity/identity.go
pkg/sanity/node.go
pkg/sanity/sanity.go
pkg/sanity/tests.go
test/co_test.go
test/driver_test.go

This fixes issue #89 (deleting volumes on test failure, unique volume names) and simplifies the code a bit.

test suite reorganization

---

.gitignore
pkg/sanity/controller.go

The CSI spec doesn't require that NextToken is an integer, it should
be treated as an opaque string, therefore remove an assertion that
assumes it is an integer.
Fixes #104

Remove bad assertion in ListSnapshots test

---

hack/_apitest/api_test.go
hack/_embedded/embedded_test.go
hack/e2e.sh
pkg/sanity/sanity.go

This uses the same approach as PR #98 to combat connection issues (connecting only once per process), but implements it so that the tests can still be embedded, by caching the existing connection in the SanityContext.
@darkowlzz I liked the API tests that you added to PR #98, so I've copied your commit into this PR and extended the one about embedding so that it actually catches when the tests (incorrectly) try to use their own Before/AfterSuite functions.

pkg/sanity: Use a single grpc connection via caching in SanityContext

---

pkg/sanity/controller.go

Create 2 new tests, one for a volume with a maximum-length name,
and one for a snapshot with maximum-length name. These tests are
intended to catch bugs where plugin authors use the value of the
name field in a context where 128 characters exceeds a limit in
some other system.
Fixes #107

Add tests for long names

---

pkg/sanity/controller.go

Remove snapshot invalid token test, modify the workflow for creating a
snapshot with the same name but different volume source id in order to
use valid volume id.

Fix snapshot test

---

driver/driver.go
mock/main.go
mock/service/controller.go
mock/service/identity.go
mock/service/node.go
mock/service/service.go

For CO (Kubernetes) e2e test we need a driver that:
1. Can optionally skip attach.
2. Has configurable driver name (so we can run multiple drivers + multiple tests in parallel).
3. Log all CSI calls (as json) so a test can check that the CO sent the right calls.

Update mock driver for testing

---

cmd/csi-sanity/sanity_test.go
pkg/sanity/controller.go
pkg/sanity/sanity.go

This is a relatively naive attempt to implement some functionality I'd like to have for my CSI driver development, namely the ability to specify `VolumeParameters` for my test volumes.
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

Add volume parameters to sanity tests

---

.travis.yml
utils/safegoroutinetester.go

This PR makes travis.yaml look like in the other kubernetes-csi repos. As side-effect, new image should be built to fix https://github.com/kubernetes-csi/csi-test/issues/127
Fixes: https://github.com/kubernetes-csi/csi-test/issues/127
@pohly @lpabon

Fix canary builds

---

mock/main.go
mock/service/node.go
mock/service/service.go

Allow configurable attach limit.

Add support for attach limits to the mock driver

---

pkg/sanity/controller.go

Fix listsnapshot clean up

---

.gitignore
CONTRIBUTING.md
OWNERS
README.md
SECURITY_CONTACTS
hack/_apitest/api_test.go
hack/_embedded/embedded_test.go
hack/e2e.sh
pkg/sanity/controller.go
pkg/sanity/sanity.go

By mistake, I had released 0.3.0-3 from master which used the latest CSI spec instead of 0.3.0. This PR is created to cherry-pick all the changes from master to the v0.3.0 branch up to the version which changed the CSI spec in the vendor dir.

Update v0.3.0 branch to release 0.3.0-4

---

pkg/sanity/controller.go

Plugin's PUBLISH_READONLY capability should be verified
before publishing volume in readonly mode.

Fix controller publish in readonly mode

---

mock/service/node.go
pkg/sanity/node.go

This change implements `NodeGetVolumeStats()` for the mock driver and
adds sanity tests for the same.

sanity/mock: Add NodeGetVolumeStats sanity check

---

pkg/sanity/sanity.go

Close the gRPC connection properly at the end of the test to avoid any
transport error in the subsequent connections.

sanity: close connection

---

pkg/sanity/controller.go
pkg/sanity/node.go

Negative tests that expect the plugin to return InvalidArgument because
no capabilities were supplied must use a real volume, otherwise plugins
might return NotFound instead.
Fixes #148

Use real volumes when testing no capabilities

---

cmd/csi-sanity/sanity_test.go
pkg/sanity/sanity.go

This flag specifies a JUnit XML file which contains test results.
Fixes https://github.com/kubernetes-csi/csi-test/issues/146

Add '--csi.junitfile` flag

---

mock/service/controller.go

Found with "go vet":
mock/service/controller.go:511: Entry.Infof format %s has arg requestBytes of wrong type int64

mock: fix log format string

---

pkg/sanity/sanity.go

When not reusing an old connection because the address has changed, we
should better close the old connection. Otherwise gRPC keeps
attempting to connect to it, which leads to more and more log output
the more old connection we leave open.

sanity: close old connection when creating a new one

---

driver/mock.go

This is cherry-pick of https://github.com/kubernetes-csi/csi-test/pull/165 into release-1.0 branch.

Cherry-pick #165 to release-1.0: Add StartOnAddress function to listen on unix:// paths

---

Makefile

We should not hardcode official release versions in the Makefile.
The v1.0.2 image just got overridden. @lpabon can you figure out how to restore the original 1.0.2 image?

Change image tag to v1.0-canary

---

cmd/mock-driver/main.go
mock/service/controller.go
mock/service/service.go

Make controller capacity `ControllerServiceCapability_RPC_EXPAND_VOLUME` configurable so that we can test a driver that doesn't support expansion. See https://github.com/kubernetes-csi/csi-test/pull/160#discussion_r254461959

make controller expansion capacity configurable

---

Gopkg.toml

This is a workaround for https://github.com/golang/dep/issues/1799.
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

Add fsnotify dep workaround

---

cmd/csi-sanity/sanity_test.go
cmd/mock-driver/main.go
hack/_apitest/api_test.go
hack/_embedded/embedded_test.go
hack/e2e.sh
mock/service/controller.go
mock/service/service.go
pkg/sanity/controller.go
pkg/sanity/sanity.go

This adds a test for ControllerPublishVolume to check the maximum volume
attachment on a node.
It also sets max attach limit in the mock driver to 2 and adds a check
in the driver for the number of volume attachments before publishing a
new volume.
ControllerPublishVolume [Max volumes attached](https://github.com/container-storage-interface/spec/blob/release-1.0/spec.md#controllerpublishvolume-errors) error.

sanity: Add max volumes attached test

---

cmd/csi-sanity/sanity_test.go
cmd/mock-driver/main.go
driver/driver-controller.go
driver/driver-node.go
driver/driver.go
hack/e2e.sh
pkg/sanity/controller.go
pkg/sanity/node.go
pkg/sanity/sanity.go

This change adds a new flag `controllerendpoint` to csi-sanity which
could be used to pass a separate controller endpoint for CSI drivers
that have separate controller and node services
It also modifies the mock driver to support separate controller and node
component mode when CSI_CONTROLLER_ENDPOINT env var is passed to it.
Two separate unix domain sockets are created and the csi-sanity connects
to the appropriate socket while running the RPCs.
Adds a new e2e test section to test this setup.
Fixes #142

Add support for separate controller and node addresses

---

mock/service/controller.go

The mock driver already supports publishing readonly volume capability,
but since readonly capability was added at a later stage in the CSI spec,
a test that depended on readonly capability was being skipped. This
change adds PUBLISH_READONLY capability to the mock driver controller
to avoid skipping volume publish incompatiblity test.
Earlier:
```
Ran 60 of 61 Specs in 0.040 seconds
SUCCESS! -- 60 Passed | 0 Failed | 0 Pending | 1 Skipped
```
With this change:
```
Ran 61 of 61 Specs in 0.037 seconds
SUCCESS! -- 61 Passed | 0 Failed | 0 Pending | 0 Skipped
```

mock: add PUBLISH_READONLY capability to driver

---

pkg/sanity/sanity.go

The assumption that sc.conn always gets set turned out to be
false. The reason probably was running with such a high number of
Ginkgo nodes that some nodes never had to execute any test.

sanity: avoid nil access for connection

---

mock/service/controller.go
mock/service/service.go
pkg/sanity/controller.go

Adds support for volume creation from source volume and snapshot in the
mock driver and the corresponding sanity tests.
Also, adds volume CLONE_VOLUME capability to the mock driver's supported
capability list.
Fixes #118

Add tests for volume creation from source

---

pkg/sanity/node.go

Without this patch, the validation of a node service that implements volume expansion always fails:
```
• Failure [0.001 seconds]
AWS EBS CSI Driver
/home/fjb/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/sanity/sanity_test.go:64
Node Service
/home/fjb/pkg/mod/github.com/kubernetes-csi/csi-test@v1.1.1/pkg/sanity/tests.go:44
NodeGetCapabilities
/home/fjb/pkg/mod/github.com/kubernetes-csi/csi-test@v1.1.1/pkg/sanity/node.go:108
should return appropriate capabilities [It]
/home/fjb/pkg/mod/github.com/kubernetes-csi/csi-test@v1.1.1/pkg/sanity/node.go:109
Unknown capability: EXPAND_VOLUME
```
/kind bug
/assign @gnufied

Add missing expand volume capability

---

mock/service/controller.go
pkg/sanity/controller.go

- Adds test for expecting `ABORTED` gRPC code when an invalid
starting_token is passed to `Controller.ListVolumes()` and when the
starting_token value is greater than the actual number of volumes.
- Adds a `Controller.ListVolumes()` test to check for the
change in volume list when a volume is added and removed.
- Adds `Controller.ListVolumes()` test to pass `MaxEntries` and receive a
`NextToken` and ensure paginated list volumes works.

sanity: Add ListVolumes test to check starting token and next token

---

hack/e2e.sh

All cleanup actions are now done via EXIT traps in subshells. That
removes the need to capture return codes.
The "Killed" message for the mock driver is removed, it looked odd to
run the script and have it end with that message.
Previously, "make test" when invoked from another script hang with
some mock driver processes still running. These changes fix that.

e2e.sh: simplify cleanup

---

pkg/sanity/cleanup.go

https://github.com/kubernetes-csi/csi-test/pull/159 introduced the
ability to use different paths for each tests via external commands or
callbacks, but it missed two lines in the cleanup code which also have
to use the actual paths instead of the configured paths.

sanity: use correct path during cleanup

---

hack/e2e.sh
release-tools/travis.yml

Imports the latest csi-release-tools and fixes a compatibility problem in e8500f2.

update to Go 1.12.4

---

Gopkg.lock
pkg/sanity/cleanup.go
pkg/sanity/controller.go
pkg/sanity/node.go
pkg/sanity/sanity.go
pkg/sanity/tests.go
utils/grpcutil.go

/kind feature
This enables better testing over TCP (dead connection detection) and reuse of the csi-sanity infrastructure in custom test suites.
This *extends* the API of the package and thus is a minor update.
```release-note
the csi-sanity connection setup can be used in custom test suites
```

Reuse testing api

---

pkg/sanity/controller.go

In one of ListVolumes tests, newly created volume ids were not captured. Though the test has needed cleaning up code, it was affected because of the empty newVolIDs array. This leads to leaking of volumes.
/kind bug

sanity: capture newly created volume IDs

---

pkg/sanity/controller.go
pkg/sanity/node.go

>
/kind bug
> /kind design
> /kind flake
Fixes #194 
```release-note
NONE
```

CreateVolume respects the topology requirements of the node

---

pkg/sanity/controller.go
pkg/sanity/sanity.go

Adds tests for ControllerExpandVolume capability. Tests for OFFLINE
VolumeExpansion are not included.
/kind test-case
csi-test do not support ControllerExpandVolume capability yet. This PR adds three very basic tests for this.
Not sure about the /kind test-case but there was no fitting kind ;)
```release-note
Added tests for ControllerExpandVolume
```

Implement ControllerExpandVolume tests for Online expansion.

---

pkg/sanity/controller.go

/kind bug
When listing volumes using pagination we must treat the "next_token"
field as opaque data and not make assumptions about what's in it.
This patch removes tests that assume tokens are integers and that they
represent the number of volumes that have been listed, replacing one of
them with one to check that pagination works as expected when new
volumes are created and old ones deleted between page requests.
Fixes #204 
```release-note
Remove volume listing tests that assumed tokens were integers and replace them with one that confirms pagination works when adding/deleting volumes between page …
```

Closes #204 - Treat list volume tokens as opaque

---

pkg/sanity/controller.go
pkg/sanity/identity.go
pkg/sanity/node.go

/kind bug
**What this PR does / why we need it**: providing CONTROLLER_SERVICE is optional. Node tests should not fail if it's not provided. With these changes, it's possible to do
$ csi-sanity --csi.endpoint=./csi.sock -ginkgo.skip='\[Controller.Server\]'
to test a node-only plugin against node-specific tests
Fixes #
```release-note
NONE
```

Tolerate nil capabilities for plugins that don't provide CONTROLLER_SERVICE

---

cmd/mock-driver/main.go
mock/service/node.go
mock/service/service.go

/kind feature
This enables testing of recent csi-mock with recent Kubernetes by allowing the Kubernetes tests to make the TargetPath existence check more permissive and the testing of ephemeral inline volumes in Kubernetes.
All of the "CSI Mock volume" tests (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/csi_mock_volume.go#L59) still pass with this new driver.
```release-note
csi-mock driver now supports relaxing the target path check (--permissive-target-path) and ephemeral inline volumes
```

ephemeral volumes

---

pkg/sanity/cleanup.go

/kind feature
Cleaning up may have leaked volumes due to an incorrect target path. Stress testing may use multiple goroutines, and then data structures in the cleanup code must be protected.
The concurrency support was developed for a stress test in PMEM-CSI. That's also were we noticed the leaked volumes.
```release-note
the sanity volume code can be used concurrently and avoids a potential volume leak because of an incorrect target path
```

cleanup fix + enhancement

---

pkg/sanity/controller.go
pkg/sanity/sanity.go

>
> /kind design
> /kind flake
/kind bug
A few sanity tests (i.e, ControllerExpandVolume) failed with our CSI driver due to missing or empty secrets provided in the ‘ControllerExpandVolumeRequest’. This is required by the CSI driver to fetch/get the volume from the backend storage.
so, this PR implements the changes to include secrets in the ControllerExpandVolumeRequest.
Fixes #215 …

Pass ControllerExpandVolumeSecret info to the VolumeExpand CSI tests

---

pkg/sanity/sanity.go

/kind bug
When adding IDGen, only one of the two code paths that trigger testing
was updated such that it sets a default ID generator when the config
doesn't already have one. GinkgoTest was not updated.
As a result, existing E2E suites which use GinkgoTest and don't set the
new field crash at runtime with a nil pointer error when updated to
csi-test 2.2.0.
Updating the instance provided by the caller is also a bit
questionable because it is an undocumented side effect. It's cleaner
to treat the struct as read-only and implement the fallback in an
accessor function.
We should create a 2.2.1 with this fix...
```release-note
fix nil …
```

sanity: fix nil pointer error for IDGen when using Ginkgo suite

---

pkg/sanity/controller.go

/kind bug
Volume created by testcase is not adding to cleanup list, hence it results in
volume leaking. This change fixes this issue.
The side effect of this testcase fix discovered a minor issue in mock driver implementation.
Which was hidden due to the leftover volume created by above testcase.
```release-note
NONE
```

sanity: Disable ListVolumes pagination test

---

mock/service/controller.go

/kind bug
`"should create volume from an existing source volume"`  test on mock driver fails when creating a new volume from existing volume stored at index 0. due to the wrong check in the driver code. This change fixes the issue.
```release-note
None
```

Fix mock driver

---

CHANGELOG-2.3.md

Once this is merged, we can release v2.3.0.
```release-note
NONE
```

CHANGELOG-2.3.md: content for v2.3.0

---

cmd/csi-sanity/sanity_test.go
cmd/mock-driver/main.go
driver/mock.go
go.mod
mock/service/service.go
pkg/sanity/sanity.go
test/co_test.go
test/driver_test.go
v3/README.md
v3/driver/driver-controller.go
v3/driver/driver-node.go
v3/driver/driver.go
v3/driver/driver.mock.go
v3/driver/mock.go
v3/mock/cache/SnapshotCache.go
v3/mock/service/controller.go
v3/mock/service/identity.go
v3/mock/service/node.go
v3/mock/service/service.go
v3/pkg/sanity/cleanup.go
v3/pkg/sanity/controller.go
v3/pkg/sanity/identity.go
v3/pkg/sanity/node.go
v3/pkg/sanity/sanity.go
v3/pkg/sanity/tests.go
v3/pkg/sanity/util.go
v3/utils/grpcutil.go
v3/utils/safegoroutinetester.go

As stated in this post:
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher
modules that released a version higher than 1 need to put the version
into the package path.
>
/kind bug
> /kind design
> /kind flake
When 2.3.0 introduced go modules, the package paths where not updated. Therefore
this module cannot be imported as version 2.3.0 since go mod will complain: 
```console
go.mod:12: require github.com/kubernetes-csi/csi-test: version "v2.3.0" invalid: module contains a go.mod file, …
```

Fix go module requirements for semantic versioning

---

cmd/csi-sanity/sanity_test.go
pkg/sanity/controller.go
pkg/sanity/sanity.go

Signed-off-by: Xin Wang <wileywang@yunify.com>
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #235 
```release-note
Add '--csi.testsnapshotparameters' flag
```

Add snapshot parameter flag

---

cmd/csi-sanity/sanity_test.go
hack/_apitest/api_test.go
hack/_apitest2/api_test.go
hack/_embedded/embedded_test.go
pkg/sanity/cleanup.go
pkg/sanity/controller.go
pkg/sanity/identity.go
pkg/sanity/node.go
pkg/sanity/sanity.go
pkg/sanity/tests.go

/kind api-change
As discussed in https://github.com/kubernetes-csi/csi-test/pull/220, the current API makes it hard to introduce new config fields which don't have the nul value as default. The new `NewTestConfig` addresses that.
As were are breaking the API with that already, several other shortcomings can also be addressed.
This is meant to go into v3.0.0 together with PR #232 .
/cc @misterikkit @davidz627 
```release-note
revised sanity API: more consistent naming, NewTestConfig must be used
```

clean up configuration handling

---

cmd/csi-sanity/Makefile
cmd/csi-sanity/main.go
pkg/sanity/sanity.go

/kind feature
This enables "go get github.com/kubernetes-csi/csi-test/cmd/csi-sanity" and gets rid of useless "-test.*" parameters.
Builds on top of PR #233 which needs to be merged first.
```release-note
`go get github.com/kubernetes-csi/csi-test/cmd/csi-sanity` now works
```

csi-sanity binary

---

cmd/mock-driver/main.go
driver/mock.go
hack/e2e.sh
pkg/sanity/sanity.go
test/driver_test.go
utils/grpcutil.go
vendor/modules.txt

/kind api-change
Enabling gRPC keepalive breaks connections if the CSI driver isn't prepared for it. When testing this is was useful to also support TCP in the mock driver.
Fixes #238 
Depends on PR #233 
```release-note
gRPC keepalive is no longer enabled by default and must be added to dial options in `TestConfig` if needed
```

keepalive API

---

CHANGELOG-3.0.md

This is the last step before doing a v3.0.0 release.
Related-to https://github.com/kubernetes-csi/csi-test/issues/237
<!--
```release-note
NONE
```

CHANGELOG-3.0.md: document v3.0.0

---

pkg/sanity/README.md

The change updates the `pkg/sanity` Go driver usage instructions in the README.
It seems like the approach to putting together a test configuration has changed since it was previously written down.
```release-note
NONE
```
/sig storage

Update pkg/sanity Go driver usage README instructions

---

pkg/sanity/node.go

/kind feature
Adds `NodeUnpublishVolume` test for when the volume is missing.
The spec mandates that such cases should return NOT_FOUND responses ([reference](https://github.com/container-storage-interface/spec/blob/4731db0e0bc53238b93850f43ab05d9355df0fd9/spec.md#nodeunpublishvolume-errors)).
The mock driver already implements the right behavior.
```release-note
Add NodeUnpublishVolume test for when the volume is missing
```

Add NodeUnpublishVolume test for when the volume is missing

---

.prow.sh
release-tools/README.md
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/prow.sh

Commit summary:
5f74333 prow.sh: also configure feature gates for kubelet
84f78b1 prow.sh: generic driver installation
fa90abd fix incorrect link
ac8a021 Document the process for releasing a new sidecar
6582f2f Update hostpath driver version to get fix for connection-timeout
8191eab Update snapshotter to version v2.0.0
8b0316c Fix overriding of junit results by using unique names for each e2e run
af9549b Update prow hostpath driver version to 1.3.0-rc2
fc80975 Fix version_gt to work with kubernetes prefix
b98b2ae Enable snapshot tests in 1.17 to be run in non-alpha jobs.
a4e6299 fix syntax for ppc64le build
4ad6949 Improve snapshot pod running checks and improve version_gt
53888ae Improve README by adding an explicit Kubernetes dependency section
9a7a685 Create a kind cluster with two …

master: update release-tools

---

cmd/csi-sanity/main.go
pkg/sanity/controller.go
pkg/sanity/node.go
pkg/sanity/sanity.go

**What type of PR is 
/kind feature
It adds raw volumes tests.
Fixes #174
```release-note
csi-sanity --csi.testvolumeaccesstype=block now runs CSI tests with raw block volumes.
```

Tests for raw block volumes are added

---

mock/service/controller.go

/kind bug
The behavior of the external-attacher recently changed
(https://github.com/kubernetes-csi/external-attacher/pull/165) such
that it now treats "not found" as real error.
The effect was that some Kubernetes E2E tests (like "CSI mock volume
CSI workload information using mock driver should not be passed when
podInfoOnMount=false") sometimes ran for over 2 minutes, just waiting
for detatch. That the test then proceeds without marking the test as
failed is a bug in the test cleanup code which [will be
fixed](https://github.com/kubernetes/kubernetes/pull/88118) once the mock driver is fixed.
This slowdown is not deterministic: sometimes the detach is done early
enough while the volume still exists.
With this change, …

mock: avoid "not found" error in ControllerUnpublishVolume

---

pkg/sanity/sanity.go
pkg/sanity/tests.go

/kind bug
When using a sequence of DescribeSanity, RegisterTestsInGinkgo,
DescribeSanity, RegisterTestsInGinkgo (i.e. embedding sanity tests in
a Ginkgo suite more than once) the first test got registered multiple
times, first by the initial RegisterTestsInGinkgo and again in the
second RegisterTestsInGinkgo.
Not only is this wrong, the locally bound variables also weren't
initialized properly by the BeforeEach functions, which could lead to
nil pointer accesses.
Found in PMEM-CSI when I reorganized our E2E test suite.
```release-note
repeatedly calling RegisterTestsInGinkgo now correctly adds tests only once
```

sanity: support embedding tests multiple time in Ginkgo

---

driver/driver.go

Dump whole error into gRPCCall logs, so we can check error code in e2e tests.
/kind feature
```release-note
"gRPCCall" logs on standard output now include "fullError" with complete error structure. Typically, it contains "code" and "message" with gRPC error.
```

Log full error code

---

pkg/sanity/sanity.go
pkg/sanity/tests.go

/kind bug
This reverts commit ddf8b3f0982c83ad64cc5ff403874b4eab1dd985. It was
meant to enable the call sequence DescribeSanity,
RegisterTestsInGinkgo, DescribeSanity, RegisterTestsInGinkgo, but that
call sequence is invalid: DescribeSanity must be called during the
init phase, then RegisterTestsInGinkgo may be called multiple times
with different configs.
That usage got broken by the commit above because the second
RegisterTestsInGinkgo then didn't add any of the tests defined by the
sanity package.
The regression was noticed when using the "fix" in PMEM-CSI. Now *both* usecases (registering existing tests and custom tests multiple times) have been verified...
**Does this PR …

sanity: support embedding tests multiple time in Ginkgo, II

---

cmd/mock-driver/main.go
mock/service/identity.go
mock/service/node.go
mock/service/service.go

For testing the upcoming "unset selected node" feature in external-provisioner.
Related-to: https://github.com/kubernetes/kubernetes/issues/72031
This could be merged as-is, but it might also make sense to first review the other PRs.
```release-note
NONE
```

Mock topology testing

---

CHANGELOG-3.1.md

/kind feature
Let's do a v3.1.0 to unblock PRs which depend on the new mock driver:
- https://github.com/kubernetes/kubernetes/pull/88118
- https://github.com/kubernetes/kubernetes/pull/89172
- https://github.com/kubernetes/kubernetes/pull/88114
```release-note
NONE
```

CHANGELOG-3.1.md: v3.1.0 release

---

pkg/sanity/controller.go

We provide tests on `ListSnapshots` for filtering by snapshot IDs and source volume IDs. However, the tests do not cover the case were snapshot listing functionality exists in general but is missing
filtering capabilities: for this scenario the existing tests yield false positives because the fixtures set up a single snapshot only.
We improve the tests by creating a number of snapshots of which a subset is expected to be found.
```release-note
NONE
```

Improve ListSnapshot filtering tests

---

pkg/sanity/controller.go

/kind bug
From the CSI spec:
> The capacity of the volume in bytes. This field is OPTIONAL. If not
> set (value of 0), it indicates that the capacity of the volume is
> unknown (e.g., NFS share).
> The value of this field MUST NOT be negative.
As such, the tests that validate the result of a `CreateVolume`
operation shall accept zero as the `capacity_bytes` of the returned
`Volume` object, when validating this value against the requested
capacity.
See: https://github.com/container-storage-interface/spec/blob/e129a75169c13bade7c7336afe21f259740ba679/spec.md#createvolume
Related to #94 but not fixing it completely (cfr. #263).
**Does this PR introduce a …

sanity: allow `Volume` `capacity_bytes` to be zero

---

README.md

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
<!--  Thanks for sending a pull request!  Here are some tips for you:
```release-note-none
```

Bump up the csi spec version mention from 0.4.0 to 1.2.0

---

pkg/sanity/node.go

/kind feature
It adds descriptions to To() expectations in `NodeUnpublishVolume`. Without these, `To()` expectations are unnecessarily difficult to understand.
Follow-up of @pohly's comment [here](https://github.com/kubernetes-csi/csi-test/pull/242#discussion_r366888878).
Relates to #242.
```release-note
NONE
```
/assign @pohly

Add descriptions to To() expectations in NodeUnpublishVolume

---

release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/prow.sh

Building / running on tests on Mac OS X does not work. This change updates the release-tools to the kubernetes-csi/csi-release-tools@9084fec which already has support for native building/compiling.
```release-note
Update release-tools to 9084fec to support native building
```

Update release-tools to support building on Mac OS X

---

pkg/sanity/node.go

> /kind bug
The "should fail when the volume is missing" test for `NodeUnpublishVolume` verifies that a `NotFound` error occurs when the endpoint is invoked for a missing volume. However, this expectation really only
holds for volume types that are locally attached, such as local disks or iscsi. Specifically, it would not hold for network-attached storage where it is fine to return `Ok` if the mount point does not exist. See also the related discussion [on Slack](https://kubernetes.slack.com/archives/C8EJ01Z46/p1576538436024100), and in particular @msau42's comments:
>Hm well it's strange.... If the mount point doesn't exist, then you return ok
>
>But if the device isn't even there, then mount also doesn't exist and you …

Remove missing volume test case for NodeUnpublishVolume

---

.cloudbuild.sh
cloudbuild.yaml
cmd/mock-driver/Dockerfile
release-tools/build.make
release-tools/cloudbuild.sh
release-tools/cloudbuild.yaml
release-tools/prow.sh

This updates release-tools and then enables cloud image
building in commit 166b78a.
Commit summary for csi-release-tools:
bd41690 cloud build: initial set of shared files
```release-note
publishing of images on k8s.gcr.io
```

master: update release-tools, enable cloud build

---

CHANGELOG-3.1.md

/kind feature
Let's do a v3.1.1 to include some fixes and have a new mock driver image in staging that we can promote.
Related-to: https://github.com/kubernetes-csi/csi-release-tools/issues/86#issuecomment-634509901
```release-note
NONE
```

CHANGELOG-3.1.md: prepare for v3.1.1

---

mock/service/controller.go
mock/service/service.go

Also Volume struct does not need mutex in it. No code is using it afaict.
/sig storage

Enforce offline volume expansion

---

pkg/sanity/controller.go

Raw volumes were added to the next cases:
- ExpandVolume [Controller Server]
- CreateSnapshot [Controller Server]
- DeleteSnapshot [Controller Server]
- ListSnapshots [Controller Server]
- ControllerPublishVolume
- CreateVolume
- from snapshot
- from source volume
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
--csi.testvolumeaccesstype=block is now also used by the …
```

Raw volumes coverage improvements

---

README.md
mock/README.md
mock/example/README.md
mock/example/deploy/csi-mock-driver-deployment.yaml
mock/example/deploy/csi-mock-driver-rbac.yaml
mock/example/pod-test.yaml
mock/example/pvc-test.yaml
mock/example/snapshot-restore-test.yaml
mock/example/snapshot-test.yaml

This commit adds an example folder which contains a deploy instruction
of the full CSI mock driver including csi-provisioner, csi-resizer,
csi-snapshotter and csi-node-driver-registrar.
This helps to playaround with the CSI mock driver to understand the
functionality.
Tested on GCP.
>
> /kind bug
> /kind design
> /kind flake
/kind example
Fixes #
This is a demo deployment of mock csi driver with all the containers.
**Does this PR …

Add mock CSI driver deploy example

---

mock/service/controller.go

>
/kind feature
This adds the LIST_VOLUMES_PUBLISHED_NODES capability to the mock. This will enable mock to be usable in cases such as CSI attacher reconciler. Ref: [this logic](https://github.com/kubernetes-csi/external-attacher/blob/298cb965f909f76f2d2dfa2062cb5e142f14b9d5/cmd/csi-attacher/main.go#L169) in the external-attacher. 
Fixes #
Used this modified csi-mock to verify this [fix](https://github.com/kubernetes-csi/external-attacher/pull/244) in external-attacher.  …

Add CSI LIST_VOLUMES_PUBLISHED_NODES to the controller in mock

---

cmd/mock-driver/main.go
driver/driver.go
go.mod
go.sum
mock/service/service.go
vendor/k8s.io/klog/.travis.yml
vendor/k8s.io/klog/CONTRIBUTING.md
vendor/k8s.io/klog/LICENSE
vendor/k8s.io/klog/OWNERS
vendor/k8s.io/klog/README.md
vendor/k8s.io/klog/RELEASE.md
vendor/k8s.io/klog/SECURITY_CONTACTS
vendor/k8s.io/klog/code-of-conduct.md
vendor/k8s.io/klog/go.mod
vendor/k8s.io/klog/go.sum
vendor/k8s.io/klog/klog.go
vendor/k8s.io/klog/klog_file.go
vendor/modules.txt

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR replaces logging information from mock CSI driver from fmt.Printf to klog
Fixes #278
After this goes to release, we might need to change other places where uses it to add "--v=5" to the startup args.
```release-note
Replace logging to klog for mock CSI driver.
```
/cc @msau42

Use klog for mock CSI driver logging

---

CHANGELOG-4.0.md

This PR adds changelog for v4.0.0.
Fixes #
```release-note
NONE
```

Add changelog for v4.0.0

---

pkg/sanity/resources.go

> /kind bug
#261 accidentally swapped the cleanup order to deleting volumes before snapshots. This represents a deviation to the previous behavior that not all CSI drivers may be able to handle. This change restores the original order.
```release-note
Restore snapshots-before-volumes cleanup order
```
/assign @pohly 
@apurv15 thanks for [reporting](https://github.com/kubernetes-csi/csi-test/pull/261#commitcomment-41920022)

Cleanup snapshots before volumes

---

pkg/sanity/controller.go

>
/kind bug
> /kind design
> /kind flake
Add volume parameters to some `CreateVolume` calls that missed it, so to comply with the `csi.testvolumeparameters` flag.
Fixes #291
```release-note
NONE
```

sanity: add missing TestVolumeParameters to CreateVolume calls

---

cmd/mock-driver/Dockerfile

>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: As distroless image is now multiarch, image push job fails on s390x and ppc64le due to lack of support.
Fixes # https://github.com/kubernetes-csi/csi-release-tools/issues/105
**Special notes for your reviewer**: Workaround to allow builds to pass while we add support to distroless image.
```release-note
Changing distroless base image from multiarch to -amd64 to fix Prow builds
```

Fix the failing multiarch builds

---

cmd/mock-driver/Dockerfile

>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Support for s390x/ppc64le has been added to distroless static/base images and hence the Dockerfiles can go back to using multiarch images.
Fixes #  kubernetes-csi/csi-release-tools#105
```release-note
Changing distroless image back to multiarch
```

Revert to multiarch distroless base

---

mock/service/node.go

/kind bug
After https://github.com/kubernetes/kubernetes/pull/88759/files we need to create the staging and target directories if they don't exist.
Fixes #304
```release-note
Updates the mock driver to create the target directory in `NodePublishVolume`, and remove it in `NodeUnpublishVolume`.
```

Create target directory if it doesn't exist

---

CHANGELOG-3.1.md

New release needed for https://github.com/kubernetes/kubernetes/pull/95739
```release-note
NONE
```

release notes for v3.1.2

---

cmd/mock-driver/main.go
internal/endpoint/endpoint.go
internal/proxy/proxy.go
internal/proxy/proxy_test.go

/kind feature
By running the mock driver in proxy mode with the csi.sock made
available via another *listening* endpoint it becomes possible to run
the actual driver code elsewhere, for example embedded inside an
e2e.test binary.
The second endpoint can be a TCP port that can be reached from outside
of a Kubernetes cluster, either via a service or port-forwarding.
The same can be done with "socat UNIX-LISTEN:/csi/csi.sock,fork
TCP-LISTEN:9000,reuseport", but the implementation inside the mock
driver has some advantages compared to that:
- the same image as for normal mock driver testing can be used
- the mock driver keeps the second listen socket open at all times,
so a client connecting to it doesn't get "connection …

mock: act as proxy

---

pkg/sanity/resources.go
pkg/sanity/tests.go

/kind cleanup
`release-tools/verify-boilerplate.sh` complains about these two files.
As the original author, Intel employee and because Intel agreed to
transfer copyright I am allowed to mark the code as owned by the
Kubernetes project.
```release-note
NONE
```

sanity: fix copyright header

---

mock/example/deploy/csi-mock-driver-deployment.yaml

/kind cleanup
This PR fixes the mock driver deployment manifest (see #318) to enable attaching, and bumps the attachment limit so users can more reliably test attach / detach behavior (for example with the [volume stress test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/volume_stress.go)).
For reference, [attachment is enabled by default, and we only allow 2 volumes attached per node by default](https://github.com/kubernetes-csi/csi-test/blob/44a753566c47af035eee63aa6fd9013e1815dfa5/cmd/mock-driver/main.go#L44,L46).
```release-note
NONE
```
/sig storage
/assign @Jiawei0227 
/assign @msau42

Enable attachment in mock driver deployment and bump attach limit

---

mock/service/controller.go

/kind bug
There's a format error that was caught by verify-typecheck.sh after importing the code into
Kubernetes:
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/drivers/csi-test/mock/service/controller.go:404:20: math.MaxUint32 (untyped int constant 4294967295) overflows int
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/drivers/csi-test/mock/service/controller.go:795:20: math.MaxUint32 (untyped int constant 4294967295) overflows int
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/drivers/csi-test/mock/service/controller.go:404:20: …

CSI mock driver: fix faulty error message

---

mock/example/deploy/csi-mock-driver-deployment.yaml
mock/service/node.go

>
/kind bug
> /kind design
> /kind flake
After #303, we need to mount the kubelet pod directory so we can create the target path. Also fix a bug with validating the csi staging directory.
Fixes #
```release-note
Add kubelet pod and csi plugin directories to mock driver manifest
```

Add kubelet directories to mock driver manifest

---

pkg/sanity/controller.go
pkg/sanity/identity.go
pkg/sanity/node.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
The default `Expect` error message when comparing gRPC status codes is
only somewhat useful on its own. Usually the message contains valuable
information to better debug the problem.
Fixes #
I only noticed this for a small subset of calls, but I figured it might
be useful for the whole file.
```release-note
NONE
```

Provide more context for status code mismatch errors

---

cmd/csi-sanity/main.go
hack/e2e.sh
pkg/sanity/node.go
pkg/sanity/sanity.go

/kind bug
https://github.com/kubernetes/kubernetes/pull/101441 deprecates removal of the CSI NodePublish target_path by the kubelet. This must be done by the CSI plugin according to the CSI spec.
This PR adds a sanity test to verify that the CSI plugin removes target_path as part of NodeUnpublish.
Fixes #336 
Yes
```release-note
Removal of the CSI nodepublish path by the kubelet is deprecated. This must be done by the CSI plugin according to the CSI spec.
```

Extend NodeUnpublish test to verify cleanup of TargetPath (#336)

---

CHANGELOG/CHANGELOG-4.2.md

A v4.2.0 release is useful for:
- publishing the new test enhancement
- announcing the deprecation of the mock driver
Please also approve PR #339 
```release-note
NONE
```

changelog for v4.2.0

---

pkg/sanity/node.go

support node VOLUME_MOUNT_GROUP cap, this is a new node capability added in CSI v1.5.0 spec
Fixes #
```release-note
support node VOLUME_MOUNT_GROUP cap in test
```

support node VOLUME_MOUNT_GROUP cap in test

---

CONTRIBUTING.md
driver/driver.go
pkg/sanity/controller.go
pkg/sanity/sanity.go

/kind feature
This PR adds ListSnapshotsSecret handling to the csi-sanity test suite. This feature is needed by CSI Drivers that require secrets in order to execute the Controller ListSnapshots function. All csi-sanity calls to ListSnapshot now pass in ListSnapshotsSecret.
Fixes #356
- Small change to correct link in CONTRIBUTING.md
- CSICreds now includes ListSnapshotsSecret
- Adjusted ListSnapshotRequest objects to include sc.Secrets.ListSnapshotsSecret
- Also passing sc.Secrets.DeleteSnapshotSecret to the 'deleting the snapshot' call (separate issue)
```release-note
Users will need to add …
```

feat(ListSnapshotsSecret): csi-sanity test suite now passes secrets to ListSnapshots

---

pkg/sanity/node.go
pkg/sanity/resources.go

The lack of `ControllerPublishSupported` in `Resources` cause [this line](https://github.com/kubernetes-csi/csi-test/blob/da7a71c90b602694a44815fc4c3533e803601b87/pkg/sanity/resources.go#L295) to always return false.
Fixes #316
if you see a more elegant way to enter the `ControllerPublishSupported` into `Resources` please feel free to fix it.
```release-note
None
```

add ControllerPublishSupported

---

.github/dependabot.yaml

/kind cleanup
Automatically updating dependencies saves on manual labor. The PRs created by
the bot are also more informative.
k8s.io packages are excluded. At least the staging repos don't have API
stability guarantees and better should get updated manually.
This was copied from
https://github.com/intel/intel-device-plugins-for-kubernetes/blob/faaecec537516a71c25f4af1e42d03aca2053a87/.github/dependabot.yml#L1-L16
```release-note
NONE
```
/cc @xing-yang

GitHub: enable dependabot

---

.prow.sh

The rationale was partly flawed: not all driver versions are compatible with
all Kubernetes versions. For example, the current csi-driver-host-path v1.8.0
uses the v1 CSIDriver API and thus no longer installs in Kubernetes 1.17.
```release-note
NONE
```

.prow.sh: remove hard-coded Kubernetes version

---

release-tools/filter-junit.go
release-tools/go-get-kubernetes.sh
release-tools/prow.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Squashed 'release-tools/' changes from e4dab7f..d24254f
d24254f Merge pull request https://github.com/kubernetes-csi/csi-test/issues/202 from xing-yang/kind_0.14.0
0faa3fc Update to Kind v0.14.0 images
ef4e1b2 Merge pull request https://github.com/kubernetes-csi/csi-test/pull/201 from xing-yang/add_1.24_image
4ddce25 Add 1.24 Kind image
7fe5149 Merge pull request https://github.com/kubernetes-csi/csi-test/pull/200 from pohly/bump-kubernetes-version
70915a8 prow.sh: …

Update release tools

---

pkg/sanity/identity.go

/kind feature
The external-snapshotter is going to support [Volume Group Snapshot](kubernetes/enhancements#1551), so drivers will return the capability as well.
Fixes #
There are no tests for the new Volume Group Snapshot yet. kubernetes-csi/csi-driver-host-path#399 is the first PR for a driver to support the new ALPHA feature.
```release-note
NONE
```

Allow drivers to support the GROUP_CONTROLLER_SERVICE capability

---

pkg/sanity/sanity.go

/kind bug
This PR adds a "localhost" authority to the grpc unix-socket connection to more closely resemble Kubernetes real behaviour after: https://github.com/kubernetes/kubernetes/pull/112597 in which it was introduced
There are currently no open issues regarding this
None
NONE
```release-note
Set the grpc authority to "localhost" to mimic Kubernetes behaviour
```

Add grpc authority to more closely resemble Kubernetes behaviour

---

README.md
release-tools/SIDECAR_RELEASE_PROCESS.md

fixed broken links of testgrid dashboard
>
/kind bug
> /kind design
> /kind flake
The domain name of the testgrid dashboard was updated from k8s-testgrid.appspot.com to testgrid.k8s.io. After the update old domain now throws a 'page not found error'. So fixed the broken links of testgrid dashboard.
This is related to an umbrella issue and fixes a task of the same:
https://github.com/kubernetes/test-infra/issues/30370

fixed broken links of testgrid dashboard

---

pkg/sanity/controller.go
pkg/sanity/node.go
pkg/sanity/sanity.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Always add random chars to name.
This would avoid any name conflicts. And matches k8s behaviour better.
Some system does not work if the same name is reused even after the previous resource is deleted. The idempotent state may not be cleared when resource deleted.
Fixes #
```release-note
NONE
```

always use unique name for volume and snapshot

---

pkg/sanity/resources.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
it is simpler, and easier to maintain
Fixes #
```release-note
NONE
```

replace offset args with new GinkgoHelper

---

.gitignore
Makefile
cmd/csi-sanity/main.go
hack/e2e.sh
pkg/sanity/controller.go
pkg/sanity/groupcontroller.go
pkg/sanity/node.go
pkg/sanity/sanity.go
pkg/sanity/util.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds sanity tests for the [ControllerModifyVolume](https://github.com/container-storage-interface/spec/blob/master/spec.md#controllermodifyvolume) RPC such that VolumeAttributesClass ModifyVolume enhancement KEP-3751 can be promoted to Beta
N/A
Squashed the commits, but previously we also had:
- Bump csi-driver-host-path
- Refactor sanity with ExpectErrorCode helper
- Fix uncleaned tempfile
Active …

Add ControllerModifyVolume RPC sanity tests

---

pkg/sanity/controller.go

/kind bug
Currently the VolumeContext is not populated in the ControllerPublishVolume request in the volume lifecycle tests. With this change we add the VolumeContext similar to as we do in the NodePublishVolume.
```release-note
NONE
```

Add VolumeContext in ControllerPublishVolume

---

pkg/sanity/controller.go

>
> /kind bug
> /kind design
> /kind flake
/kind feature
When developing our CSI, the volumes being created from snapshots were being deleted automatically, because the response wasn't including `ContentSource` information. Sanity tests were passing in our environment, and it was confusing to see that the tests were testing this particular case (creating a volume from snapshot) and the result was successful.
This commit made the sanity tests in our end fail with our CSI issue.
**Does …

Check ContentSource when creating volume from snapshot

---

go.mod
utils/protobuf_matcher.go

>
> /kind bug
> /kind design
> /kind flake
/feature
Source: @jsafrane's kubernetes-csi/external-provisioner#1262
gomock is not able to match newly generated Protobuf messages from csi-test, because their private fields differ. Implement a custom message matcher for projects that need to mock gRPCs can use.
See the passing tests in the following PRs for proof that this works as intended (which rely on a replace directive pointing to my fork of csi-test):
- kubernetes-csi/livenessprobe#296
- …

Add Protobuf Matcher utility

---

pkg/sanity/identity.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
The sanity test will fail to validate a CSI driver if its identity service `GetPluginCapabilities` operation returns the `csi.PluginCapability_Service_SNAPSHOT_METADATA_SERVICE` capability.
This is a new capability introduced with CSI v1.10.0 so does not impact current drivers.
Fixes https://github.com/kubernetes-csi/csi-test/issues/558 …

Added the SNAPSHOT_METADATA_SERVICE capability to the identity service sanity test

---

go.mod
go.sum
release-tools/.github/dependabot.yaml
release-tools/.github/workflows/codespell.yml
release-tools/.github/workflows/trivy.yaml
release-tools/KUBERNETES_CSI_OWNERS_ALIASES
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/cloudbuild.yaml
release-tools/contrib/get_supported_version_csi-sidecar.py
release-tools/filter-junit.go
release-tools/generate-patch-release-notes.sh
release-tools/go-modules-targeted-update.sh
release-tools/go-modules-update.sh
release-tools/prow.sh
release-tools/pull-test.sh
release-tools/verify-logcheck.sh

/kind cleanup
Update release-tools according to https://github.com/kubernetes-csi/csi-release-tools/issues/7
Related https://github.com/kubernetes-csi/csi-release-tools/pull/259
```release-note
NONE
```

Prow update master

---

pkg/sanity/controller.go

>
> /kind bug
> /kind design
> /kind flake
The name is used to achieve idempotency. To create multiple volumes, we need different names.
Fixes #
Like #476
```release-note
NONE
```

use unique name for volume

---

pkg/sanity/controller.go
pkg/sanity/node.go
pkg/sanity/sanity.go

>
/kind bug
/kind cleanup
> /kind design
> /kind flake
Use MakeCreateVolumeReq for all tests that does not care how volumes are created.
This fixes several places where TestVolumeSize is not considered.
MakeCreateVolumeReq() itself is modified to not pass LimitBytes, to match most existing cases.
Fixes some failures due to TestVolumeSize not passed to CSI.
```release-note
NONE
```

use MakeCreateVolumeReq()
