kubernetes-csi/csi-test

.travis.yml
cmd/csi-sanity/Makefile
cmd/csi-sanity/README.md
cmd/csi-sanity/sanity_test.go
glide.lock
pkg/sanity/README.md
pkg/sanity/identity.go
pkg/sanity/sanity.go
pkg/sanity/sanity_test.go

This is just the beginning of the framework. But I wanted to get acceptance on its architecture before continuing.
Currently, it only tests the Identity Server.

Sanity Test Suite: Initial Framework

---

hack/e2e.sh
pkg/sanity/controller.go

Closes #26 
Closes #16 
Closes #19

Controller Sanity Tests

---

cmd/csi-sanity/sanity_test.go
driver/driver.go
pkg/sanity/controller.go
pkg/sanity/identity.go
test/driver_test.go
utils/grpcutil.go

* add uds support fo csi test.
* remove `.` from logs.

Support Unix Domain Socket for CSI Test

---

hack/e2e.sh

sanity: Update e2e

---

hack/e2e.sh

e2e: Cleanup old files on failure

---

.gitignore
pkg/sanity/controller.go

sanity: DeleteVolume  Closes #17

Add some controller tests

---

pkg/sanity/controller.go

sanity: ValidateVolumeCapabilities Closes #20

Add tests for controller

---

pkg/sanity/controller.go

sanity: ControllerPublishVolume Closes #22 
sanity: ControllerUnpublishVolume Closes #21

Add tests for Controller Publish/UnPublish Volume

---

pkg/sanity/node.go

sanity: NodeGetCapabilities Closes #14 
sanity: NodeProbe Closes #12 
sanity: GetNodeID Closes #11 
sanity: NodePublishVolume Closes #10 #15 
sanity: NodeUnpublishVolume Closes #13

Add tests for Node

---

hack/e2e.sh
pkg/sanity/controller.go

Remove MOCKERRORS

---

pkg/sanity/controller.go

fix ControllerGetCapabilities test

---

pkg/sanity/node.go

Remove requirement for non-nil node capabilities

---

.gitignore
pkg/sanity/README.md

The original sample is using BeforeEach/AfterEach in a problematic way.

Update README for sanity test using Ginkgo.

---

pkg/sanity/controller.go

fix https://github.com/kubernetes-csi/csi-test/issues/114
/assign @lpabon @xing-yang @jingxu97

remove test case for starting_token when ListSnapshots

---

pkg/sanity/controller.go

Add PUBLISH_READONLY capability to Controller Caps

---

pkg/sanity/controller.go

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

Add ControllerServiceCapability_RPC_CLONE_VOLUME to GetCapabilities.

---

OWNERS

propose adding jan as an approver to have more spread out approver permissions in this repo.

Propose adding jan as an approver

---

cmd/csi-sanity/README.md
driver/driver.go
mock/mocksecret.yaml
pkg/sanity/controller.go
pkg/sanity/sanity.go

Add secrets to ValidateVolumeCapabilitiesRequest

---

pkg/sanity/controller.go

Just some improvements to the wording of the snapshot specs.

grammar fixes for snapshot tests

---

.prow.sh
Makefile

"test-sanity" wasn't listed in the JUnit file although it ran.

Prow testing: update csi-release-tools, fix reporting

---

CHANGELOG-2.1.md

It prepares for a v2.1.0 release.
```release-note
NONE
```
/assign @msau42

Add 2.1 changelog

---

CHANGELOG-2.2.md

Changelog for v2.2.0
/assign @msau42 @lpabon 
/cc @jsafrane 
```release-note
NONE
```

Add v2.2.0 changelog

---

cmd/csi-sanity/sanity_test.go

Signed-off-by: Xin Wang <wileywang@yunify.com>
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #218 
```release-note
Add '--csi.testvolumeexpandsize` flag
```

Add expand volume increment target flag

---

go.mod
go.sum
pkg/sanity/controller.go
vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
vendor/modules.txt

/kind cleanup
/assign @lpabon @msau42 
```release-note
Update CSI Spec to v1.2.0
```

Update vendored CSI Spec to v1.2.0 and add LIST VOLUMES PUBLISHED NODES capability to appropriate capabilities

---

pkg/sanity/controller.go

Signed-off-by: Utkarsh Mani Tripathi <utkarsh.tripathi@mayadata.io>
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR add test volume parameters for ExpandVolume test case.
Fixes #
yes
```release-note
This commit fixes an issue where expand volume RPC requests were failing, since
volume parameters were missing from the test case.
```

Add parameters in ExpandVolume rpc call

---

driver/driver.mock.go

/kind feature
I need this method to implement unit test for external-health-monitor
Fixes #
```release-note
None
```

feature: add mock method of ControllerGetVolume

---

CHANGELOG-4.0.md

This adds changelog for 4.0.1.
Fixes #
```release-note
NONE
```

Add changelog for 4.0.1

---

mock/service/node.go

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Updates the mock driver to create the target directory in `NodePublishVolume`, and remove it in `NodeUnpublishVolume`.
```

Cherry pick #303 to release-3.1: Create target dir if it doesn't exist

---

cmd/mock-driver/main.go
driver/driver.go

/kind cleanup
This PR adds missing error checks
Fixes #
```release-note
NONE
```

Add error checks

---

.prow.sh
cmd/csi-sanity/Makefile
cmd/csi-sanity/main.go
cmd/mock-driver/Dockerfile
cmd/mock-driver/main.go
driver/driver-controller.go
driver/driver-node.go
driver/driver.go
driver/mock.go
hack/_apitest/api_test.go
hack/_apitest2/api_test.go
hack/_embedded/embedded_test.go
hack/e2e.sh
internal/endpoint/endpoint.go
mock/cache/SnapshotCache.go
mock/service/controller.go
mock/service/hooks-const.go
mock/service/identity.go
mock/service/node.go
mock/service/service.go
pkg/sanity/controller.go
pkg/sanity/identity.go
pkg/sanity/node.go
pkg/sanity/sanity.go
pkg/sanity/util.go
test/co_test.go
test/driver_test.go
utils/safegoroutinetester.go

/kind cleanup
Update the copyright from 4 years ago and donate to the CNCF/Kubernetes foundation
```release-note
NONE
```

Donate csi-test to the CNCF/Kubernetes foundation

---

CHANGELOG/CHANGELOG-4.1.md
README.md
mock/README.md

Let's tag v4.1.0.
```release-note
NONE
```

release v4.1.0

---

pkg/sanity/resources.go

/kind cleanup
The error message was wrong.
```release-note
NONE
```

Fix error message for snapshot cleanup

---

CHANGELOG/CHANGELOG-4.4.md

>
> /kind bug
> /kind design
> /kind flake
Add changelog for v4.4
Fixes #
```release-note
NONE
```

Add changelog for v4.4

---

CHANGELOG/CHANGELOG-5.0.md
cmd/csi-sanity/main.go
driver/mock.go
go.mod
hack/_apitest/api_test.go
hack/_apitest2/api_test.go
hack/_embedded/embedded_test.go
internal/proxy/proxy.go
pkg/sanity/sanity.go
test/co_test.go
test/driver_test.go

The switching to Gingko v2 is potentially breaking users, so it gets
treated as an API change.
```release-note
NONE
```

prepare v5.0.0 release

---

pkg/sanity/sanity.go

> /kind bug
avoid close of closed conn when the controller address of config is empty
```release-note
NONE
```

avoid close of closed conn when the controller address of config is empty

---

pkg/sanity/identity.go

```release-note
controller service add identity service sanity test
```

controller service add identity service sanity test

---

CHANGELOG/CHANGELOG-5.1.md

Fixes #
```release-note
NONE
```

Add changelog for v5.1.0

---

CHANGELOG/CHANGELOG-5.2.md

Add changelog for v5.2.0.
Fixes #
```release-note
NONE
```

Add changelog for v5.2.0

---

pkg/sanity/controller.go

>
/kind bug
> /kind design
> /kind flake
wait for snapshot ReadyToUse before using
Fixes test failure due to not ready snapshots
```release-note
NONE
```

wait for snapshot ReadyToUse before using

---

cmd/csi-sanity/Makefile

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
For example, when checking out this PR,
current `git describe` shows: v1.1.0-693-gcf1f118
`git describe --tags` shows: v5.2.0-7-gcf1f118
Fixes #
```release-note
NONE
```

use git describe --tags for version

---

CHANGELOG/CHANGELOG-5.3.md

>
> /kind bug
> /kind design
> /kind flake
Adds changelog for csi-test v5.3.0 ahead of its release. 
Fixes #
```release-note
NONE
```

Add changelog for v5.3.0
